version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: DB2
    volumes:
      - ./sql/create_populate_pais.sql:/docker-entrypoint-initdb.d/01_pais.sql
      - ./sql/create_populate_participante.sql:/docker-entrypoint-initdb.d/02_participante.sql
      # - ./sql/ex1-b.sql:/docker-entrypoint-initdb.d/03_ex1-b.sql
      # - ./sql/ex1-c.sql:/docker-entrypoint-initdb.d/04_ex1-c.sql
      # - ./sql/ex1-d.sql:/docker-entrypoint-initdb.d/05_ex1-d.sql