CREATE TABLE IF NOT EXISTS pais (
  nroConsecutivo SMALLSERIAL NOT NULL,
  nome VARCHAR(50) NOT NULL,
  nroClubesDeXadrez INT NOT NULL,
  PRIMARY KEY (nroConsecutivo)
);

insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 45);
insert into pais (nome, nroClubesDeXadrez) values ('China', 38);
insert into pais (nome, nroClubesDeXadrez) values ('China', 82);
insert into pais (nome, nroClubesDeXadrez) values ('Philippines', 77);
insert into pais (nome, nroClubesDeXadrez) values ('China', 60);
insert into pais (nome, nroClubesDeXadrez) values ('France', 95);
insert into pais (nome, nroClubesDeXadrez) values ('Russia', 53);
insert into pais (nome, nroClubesDeXadrez) values ('Brazil', 30);
insert into pais (nome, nroClubesDeXadrez) values ('Japan', 52);
insert into pais (nome, nroClubesDeXadrez) values ('Russia', 9);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 22);
insert into pais (nome, nroClubesDeXadrez) values ('Yemen', 80);
insert into pais (nome, nroClubesDeXadrez) values ('Madagascar', 75);
insert into pais (nome, nroClubesDeXadrez) values ('China', 42);
insert into pais (nome, nroClubesDeXadrez) values ('Sweden', 33);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 44);
insert into pais (nome, nroClubesDeXadrez) values ('Morocco', 27);
insert into pais (nome, nroClubesDeXadrez) values ('Czech Republic', 36);
insert into pais (nome, nroClubesDeXadrez) values ('Sweden', 11);
insert into pais (nome, nroClubesDeXadrez) values ('France', 88);
insert into pais (nome, nroClubesDeXadrez) values ('France', 51);
insert into pais (nome, nroClubesDeXadrez) values ('United States', 17);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 81);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 7);
insert into pais (nome, nroClubesDeXadrez) values ('China', 68);
insert into pais (nome, nroClubesDeXadrez) values ('Brazil', 94);
insert into pais (nome, nroClubesDeXadrez) values ('Poland', 91);
insert into pais (nome, nroClubesDeXadrez) values ('France', 37);
insert into pais (nome, nroClubesDeXadrez) values ('Venezuela', 98);
insert into pais (nome, nroClubesDeXadrez) values ('South Africa', 25);
insert into pais (nome, nroClubesDeXadrez) values ('Poland', 75);
insert into pais (nome, nroClubesDeXadrez) values ('Portugal', 51);
insert into pais (nome, nroClubesDeXadrez) values ('Portugal', 58);
insert into pais (nome, nroClubesDeXadrez) values ('Russia', 4);
insert into pais (nome, nroClubesDeXadrez) values ('Japan', 16);
insert into pais (nome, nroClubesDeXadrez) values ('Uzbekistan', 65);
insert into pais (nome, nroClubesDeXadrez) values ('China', 70);
insert into pais (nome, nroClubesDeXadrez) values ('Sweden', 77);
insert into pais (nome, nroClubesDeXadrez) values ('Czech Republic', 56);
insert into pais (nome, nroClubesDeXadrez) values ('Poland', 14);
insert into pais (nome, nroClubesDeXadrez) values ('China', 27);
insert into pais (nome, nroClubesDeXadrez) values ('Bolivia', 38);
insert into pais (nome, nroClubesDeXadrez) values ('Brazil', 7);
insert into pais (nome, nroClubesDeXadrez) values ('China', 85);
insert into pais (nome, nroClubesDeXadrez) values ('China', 85);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 53);
insert into pais (nome, nroClubesDeXadrez) values ('Philippines', 45);
insert into pais (nome, nroClubesDeXadrez) values ('Bosnia and Herzegovina', 34);
insert into pais (nome, nroClubesDeXadrez) values ('France', 77);
insert into pais (nome, nroClubesDeXadrez) values ('China', 12);
insert into pais (nome, nroClubesDeXadrez) values ('China', 73);
insert into pais (nome, nroClubesDeXadrez) values ('Russia', 95);
insert into pais (nome, nroClubesDeXadrez) values ('United States', 62);
insert into pais (nome, nroClubesDeXadrez) values ('France', 60);
insert into pais (nome, nroClubesDeXadrez) values ('China', 42);
insert into pais (nome, nroClubesDeXadrez) values ('Tunisia', 82);
insert into pais (nome, nroClubesDeXadrez) values ('Poland', 80);
insert into pais (nome, nroClubesDeXadrez) values ('China', 37);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 9);
insert into pais (nome, nroClubesDeXadrez) values ('Poland', 40);
insert into pais (nome, nroClubesDeXadrez) values ('United States', 16);
insert into pais (nome, nroClubesDeXadrez) values ('Brazil', 58);
insert into pais (nome, nroClubesDeXadrez) values ('Philippines', 93);
insert into pais (nome, nroClubesDeXadrez) values ('North Korea', 29);
insert into pais (nome, nroClubesDeXadrez) values ('Philippines', 22);
insert into pais (nome, nroClubesDeXadrez) values ('China', 70);
insert into pais (nome, nroClubesDeXadrez) values ('Russia', 85);
insert into pais (nome, nroClubesDeXadrez) values ('Portugal', 71);
insert into pais (nome, nroClubesDeXadrez) values ('Angola', 53);
insert into pais (nome, nroClubesDeXadrez) values ('Greece', 50);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 64);
insert into pais (nome, nroClubesDeXadrez) values ('Slovenia', 73);
insert into pais (nome, nroClubesDeXadrez) values ('Tanzania', 36);
insert into pais (nome, nroClubesDeXadrez) values ('South Africa', 30);
insert into pais (nome, nroClubesDeXadrez) values ('Russia', 71);
insert into pais (nome, nroClubesDeXadrez) values ('Greece', 35);
insert into pais (nome, nroClubesDeXadrez) values ('China', 63);
insert into pais (nome, nroClubesDeXadrez) values ('Russia', 11);
insert into pais (nome, nroClubesDeXadrez) values ('Malaysia', 99);
insert into pais (nome, nroClubesDeXadrez) values ('Colombia', 67);
insert into pais (nome, nroClubesDeXadrez) values ('China', 4);
insert into pais (nome, nroClubesDeXadrez) values ('Poland', 13);
insert into pais (nome, nroClubesDeXadrez) values ('Cameroon', 68);
insert into pais (nome, nroClubesDeXadrez) values ('France', 66);
insert into pais (nome, nroClubesDeXadrez) values ('Philippines', 82);
insert into pais (nome, nroClubesDeXadrez) values ('Brazil', 96);
insert into pais (nome, nroClubesDeXadrez) values ('Papua New Guinea', 79);
insert into pais (nome, nroClubesDeXadrez) values ('Norway', 37);
insert into pais (nome, nroClubesDeXadrez) values ('Colombia', 63);
insert into pais (nome, nroClubesDeXadrez) values ('Poland', 29);
insert into pais (nome, nroClubesDeXadrez) values ('Slovenia', 45);
insert into pais (nome, nroClubesDeXadrez) values ('Czech Republic', 52);
insert into pais (nome, nroClubesDeXadrez) values ('China', 56);
insert into pais (nome, nroClubesDeXadrez) values ('Russia', 16);
insert into pais (nome, nroClubesDeXadrez) values ('China', 85);
insert into pais (nome, nroClubesDeXadrez) values ('Nigeria', 53);
insert into pais (nome, nroClubesDeXadrez) values ('Albania', 51);
insert into pais (nome, nroClubesDeXadrez) values ('Central African Republic', 83);
insert into pais (nome, nroClubesDeXadrez) values ('China', 89);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 34);
insert into pais (nome, nroClubesDeXadrez) values ('Japan', 35);
insert into pais (nome, nroClubesDeXadrez) values ('Thailand', 18);
insert into pais (nome, nroClubesDeXadrez) values ('China', 97);
insert into pais (nome, nroClubesDeXadrez) values ('Brazil', 36);
insert into pais (nome, nroClubesDeXadrez) values ('Brazil', 17);
insert into pais (nome, nroClubesDeXadrez) values ('Yemen', 17);
insert into pais (nome, nroClubesDeXadrez) values ('France', 21);
insert into pais (nome, nroClubesDeXadrez) values ('China', 7);
insert into pais (nome, nroClubesDeXadrez) values ('China', 32);
insert into pais (nome, nroClubesDeXadrez) values ('China', 84);
insert into pais (nome, nroClubesDeXadrez) values ('Ukraine', 61);
insert into pais (nome, nroClubesDeXadrez) values ('Armenia', 85);
insert into pais (nome, nroClubesDeXadrez) values ('Finland', 50);
insert into pais (nome, nroClubesDeXadrez) values ('Argentina', 4);
insert into pais (nome, nroClubesDeXadrez) values ('China', 12);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 61);
insert into pais (nome, nroClubesDeXadrez) values ('Malaysia', 74);
insert into pais (nome, nroClubesDeXadrez) values ('United States', 97);
insert into pais (nome, nroClubesDeXadrez) values ('El Salvador', 27);
insert into pais (nome, nroClubesDeXadrez) values ('Portugal', 33);
insert into pais (nome, nroClubesDeXadrez) values ('Malta', 32);
insert into pais (nome, nroClubesDeXadrez) values ('Cameroon', 87);
insert into pais (nome, nroClubesDeXadrez) values ('China', 89);
insert into pais (nome, nroClubesDeXadrez) values ('Brazil', 87);
insert into pais (nome, nroClubesDeXadrez) values ('China', 22);
insert into pais (nome, nroClubesDeXadrez) values ('Burkina Faso', 93);
insert into pais (nome, nroClubesDeXadrez) values ('Thailand', 45);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 20);
insert into pais (nome, nroClubesDeXadrez) values ('France', 47);
insert into pais (nome, nroClubesDeXadrez) values ('Brazil', 90);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 35);
insert into pais (nome, nroClubesDeXadrez) values ('Brazil', 57);
insert into pais (nome, nroClubesDeXadrez) values ('China', 95);
insert into pais (nome, nroClubesDeXadrez) values ('Russia', 40);
insert into pais (nome, nroClubesDeXadrez) values ('Greece', 6);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 80);
insert into pais (nome, nroClubesDeXadrez) values ('Comoros', 11);
insert into pais (nome, nroClubesDeXadrez) values ('Sweden', 36);
insert into pais (nome, nroClubesDeXadrez) values ('Honduras', 99);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 73);
insert into pais (nome, nroClubesDeXadrez) values ('Indonesia', 54);
insert into pais (nome, nroClubesDeXadrez) values ('Brazil', 14);
insert into pais (nome, nroClubesDeXadrez) values ('Canada', 44);
insert into pais (nome, nroClubesDeXadrez) values ('France', 64);
insert into pais (nome, nroClubesDeXadrez) values ('Micronesia', 6);
insert into pais (nome, nroClubesDeXadrez) values ('Burkina Faso', 35);
insert into pais (nome, nroClubesDeXadrez) values ('Japan', 99);
insert into pais (nome, nroClubesDeXadrez) values ('Germany', 73);
insert into pais (nome, nroClubesDeXadrez) values ('Russia', 4);
insert into pais (nome, nroClubesDeXadrez) values ('Thailand', 72);
